name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run:  | 
        sudo apt install -y libwiringpi-dev
        make all
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: orange_pi5_fan_control
