name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
    - run:  apt install -y git build-essential
    - run: git clone https://github.com/orangepi-xunlong/wiringOP.git
    - run: cd wiringOP && ./build clean &&  ./build && ..
    - run: make all
